def find_frequent_words(text, pattern):
    dic = {}
    for i in range(0, len(text) - pattern + 1):
        val = dic.get(text[i : i + pattern], 0)
        val += 1
        dic[text[i : i + pattern]] = val

    return dic


def find_max_words(text, pattern):
    dic = find_frequent_words(text, pattern)
    max_int = max(dic.values())

    max_list = [i for i, v in dic.items() if v == max_int]
    return " ".join(max_list)


text = "CCTCTTGATCCTGGCCATCCTGGCCATCCTGGCCACCTCTTGACCTCTTGATCCTGGCCATCCTGGCCAGGTGTTCTTCCTGGCCACCTCTTGACCTCTTGAGGTGTTCTGTTACATTTCCTGGCCAGGTGTTCTTCCTGGCCATCCTGGCCACCTCTTGATCCTGGCCACCTCTTGAACTAATAGTCTCCTGGCCATCCTGGCCATCCTGGCCAACTAATAGTCGGTGTTCTACTAATAGTCGTTACATTTCCTGGCCAGTTACATTGTTACATTTCCTGGCCAGTTACATTGTTACATTGGTGTTCTACTAATAGTCGTTACATTGGTGTTCTGGTGTTCTCCTCTTGACCTCTTGAACTAATAGTCTCCTGGCCACCTCTTGAACTAATAGTCGGTGTTCTACTAATAGTCGGTGTTCTACTAATAGTCCCTCTTGAGGTGTTCTGTTACATTTCCTGGCCACCTCTTGATCCTGGCCAGTTACATTACTAATAGTCGTTACATTGTTACATTGGTGTTCTTCCTGGCCAGGTGTTCTGGTGTTCTGGTGTTCTGTTACATTCCTCTTGAGGTGTTCTCCTCTTGAGTTACATTCCTCTTGAGTTACATTCCTCTTGAACTAATAGTCTCCTGGCCAGGTGTTCTTCCTGGCCAGTTACATTCCTCTTGAGGTGTTCTACTAATAGTCACTAATAGTCGTTACATTCCTCTTGATCCTGGCCACCTCTTGAACTAATAGTCTCCTGGCCAGTTACATTTCCTGGCCAGTTACATTACTAATAGTCTCCTGGCCACCTCTTGACCTCTTGAGGTGTTCTGTTACATTGTTACATTTCCTGGCCAGTTACATTACTAATAGTCGGTGTTCTCCTCTTGAACTAATAGTCGGTGTTCTGGTGTTCTGGTGTTCTGTTACATTCCTCTTGATCCTGGCCAGTTACATTTCCTGGCCAGTTACATTACTAATAGTC"
pattern = 13

print(find_max_words(text, pattern))
